import assert from "node:assert/strict";
import { execFile } from "node:child_process";
import { once } from "node:events";
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { execFileSync } from "node:child_process";
import { createServer, type Socket } from "node:net";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { promisify } from "node:util";
import { test } from "node:test";
import { DefaultResourceLoader, SettingsManager, type ExtensionContext } from "@earendil-works/pi-coding-agent";
import { openDb } from "../src/db.ts";
import { readRecordedPlanBinding } from "../src/plan-binding.ts";
import { acceptPublication } from "../src/plan-publication-state.ts";
import { splitPublication } from "../src/plan-publication.ts";
import { resolvePublicationTarget } from "../src/plan-publication-target.ts";

const source = join(import.meta.dirname, "..");

test("raw interactive authority flows through real plan CLI and parent control without a second do confirm", { timeout: 60000 }, async () => {
  const dir = mkdtempSync(join(import.meta.dirname, "fixtures", "workflow-runtime-"));
  const runtime = mkdtempSync(join(tmpdir(), "ym-authority-"));
  const env = { ...process.env };
  const script = process.argv[1];
  const eventConnections: Socket[] = [];
  const eventServer = createServer((socket) => eventConnections.push(socket));
  let shutdown: (() => Promise<void>) | undefined;
  try {
    const eventSocket = join(runtime, "review.sock");
    eventServer.listen(eventSocket);
    await once(eventServer, "listening");
    process.env.WORKFLOW_EVENT_SOCKET = eventSocket;
    delete process.env.YOKEMATE_MODE;
    delete process.env.YOKEMATE_ROLE;
    delete process.env.HERDR_PANE_ID;
    delete process.env.YOKEMATE_PARENT_PANE;
    process.env.XDG_RUNTIME_DIR = runtime;
    process.argv[1] = join(source, "test", "fixtures", "workflow-rpc-child.mjs");
    cpSync(join(source, "src"), join(dir, "src"), { recursive: true });
    cpSync(join(source, ".pi", "extensions", "subagent"), join(dir, ".pi", "extensions", "subagent"), { recursive: true });
    mkdirSync(join(dir, ".pi", "agents", "do"), { recursive: true });
    writeFileSync(join(dir, ".pi", "agents", "do-coordinator.md"), "fixture");
    writeFileSync(join(dir, ".env.local"), "");
    const settings = join(dir, ".pi", "settings.json");
    const set = (workflowApproval: boolean, guards = {}) => writeFileSync(settings, JSON.stringify({ guardPolicy: { workflowApproval, guards } }));
    set(false);
    const folder = join(dir, "home", "knowledge", "org", "repo", "ai", "YM-1-work");
    mkdirSync(folder, { recursive: true });
    const plan = join(folder, "plan.md");
    const text = "# YM-1 — fixture\n\n## Goal\nExercise authority.\n\n## Affected repositories\n- `org/repo` — app\n\n## Steps\n1. Work\n\n## Assumptions\n- Fixture.\n\n## Out of scope\n- Production.\n\n## Acceptance\nThe fixture records the plan.\n";
    writeFileSync(plan, text);
    const clone = join(dir, "clone");
    mkdirSync(clone);
    execFileSync("git", ["init", "-b", "main", clone], { stdio: "pipe" });
    execFileSync("git", ["-C", clone, "remote", "add", "origin", "https://github.com/org/repo.git"], { stdio: "pipe" });
    const commentsFile = join(dir, "comments.json");
    writeFileSync(commentsFile, "[]");
    const shim = join(dir, "shim");
    mkdirSync(shim);
    writeFileSync(join(shim, "gh"), `#!${process.execPath}\nimport fs from "node:fs";\nconst args=process.argv.slice(2); const file=process.env.WORKFLOW_COMMENTS; const rows=JSON.parse(fs.readFileSync(file,"utf8"));\nif(args[0]==="api"){const page=Number(/&page=(\\d+)/.exec(args[1])[1]); console.log(JSON.stringify(rows.slice((page-1)*100,page*100)));}\nelse if(args[0]==="issue"&&args[1]==="comment"){let body=""; process.stdin.setEncoding("utf8"); process.stdin.on("data",c=>body+=c); process.stdin.on("end",()=>{rows.push({id:rows.length+1,body,html_url:"https://github.com/org/repo/issues/1#issuecomment-"+(rows.length+1)}); fs.writeFileSync(file,JSON.stringify(rows)); console.log("ok");});}\nelse process.exit(2);\n`, { mode: 0o755 });
    process.env.PATH = `${shim}:${process.env.PATH ?? ""}`;
    process.env.WORKFLOW_COMMENTS = commentsFile;
    const db = openDb(join(dir, "yokemate.db"));
    db.prepare("INSERT INTO project (org,repo,path,tracker,tracker_key,model) VALUES ('org','repo',?,'github','YM','test/model')").run(clone);
    const target = resolvePublicationTarget(db, "YM-1");
    assert.equal(target.type, "github");
    const scoutBytes = Buffer.from("# Scout\n\nFacts and sources.\n");
    const scout = acceptPublication(db, dir, { target: target.target, targetHash: target.targetHash, ticket: "YM-1", kind: "scout", bytes: scoutBytes, runId: "scout-run" });
    const scoutParts = splitPublication({ target: target.target, targetHash: target.targetHash, canonicalUrl: target.canonicalUrl, ticket: "YM-1", run: scout.run_id, kind: "scout", hash: scout.content_hash, bytes: scoutBytes });
    writeFileSync(commentsFile, JSON.stringify(scoutParts.map((part, index) => ({ id: index + 1, body: part.body, html_url: `${target.canonicalUrl}#issuecomment-${index + 1}` }))));
    const loader = new DefaultResourceLoader({ cwd: dir, agentDir: join(dir, "agent"), settingsManager: SettingsManager.create(dir, join(dir, "agent")), noExtensions: true, noSkills: true, noPromptTemplates: true, noThemes: true, noContextFiles: true, additionalExtensionPaths: [join(dir, ".pi", "extensions", "subagent", "index.ts")] });
    await loader.reload();
    const loaded = loader.getExtensions();
    assert.deepEqual(loaded.errors, []);
    loaded.runtime.appendEntry = () => undefined;
    const reports: unknown[] = [];
    let reportReady: (() => void) | undefined;
    loaded.runtime.sendMessage = (message) => { reports.push(message); reportReady?.(); };
    const extension = loaded.extensions[0]!;
    const tool = extension.tools.get("subagent")!.definition;
    let extraction: "none" | "advance-plan-do" | "approve-ready-do" = "none";
    let calls = 0;
    let confirms = 0;
    const notifications: string[] = [];
    const ctx = { cwd: dir, mode: "rpc", hasUI: true, sessionManager: { getSessionId: () => "parent" }, model: { provider: "test", id: "model" }, modelRegistry: {
      getAll: () => [{ provider: "test", id: "model", name: "model" }], hasConfiguredAuth: () => true,
      complete: async (_model: unknown, context: { messages: { content: string }[] }) => {
        calls++;
        const { raw, bindings } = JSON.parse(context.messages[0]!.content);
        const value = extraction === "none" ? { kind: "none" } : { kind: extraction, ticket: "YM-1", binding: extraction === "approve-ready-do" ? bindings[0].contentHash : null, actions: extraction === "approve-ready-do" ? ["do"] : ["plan", "do"], evidence: [{ start: 0, end: raw.length, text: raw }] };
        return { stopReason: "stop", content: [{ type: "text", text: JSON.stringify(value) }] };
      },
    }, ui: { setWidget() {}, notify(message: string) { notifications.push(message); }, confirm: async () => { confirms++; return true; } } } as unknown as ExtensionContext;
    for (const handler of extension.handlers.get("session_start") ?? []) await handler({ type: "session_start", reason: "startup" } as never, ctx);
    shutdown = async () => { for (const handler of extension.handlers.get("session_shutdown") ?? []) await handler({ type: "session_shutdown" } as never, ctx); };
    const input = async (text: string, source = "interactive", mode = "tui") => { for (const handler of extension.handlers.get("input") ?? []) await handler({ type: "input", source, text } as never, { ...ctx, mode } as ExtensionContext); };
    const launch = () => tool.execute("launch", { coordinator: { mode: "do", tickets: ["YM-1"] } }, undefined, () => undefined, ctx);
    const output = (result: Awaited<ReturnType<typeof launch>>) => result.content.map((part) => part.type === "text" ? part.text : "").join("\n");
    const cancel = (runId: string) => tool.execute("cancel", { cancelRun: runId }, undefined, () => undefined, ctx);
    const record = async () => (await promisify(execFile)(process.execPath, ["--experimental-strip-types", "--no-warnings", join(dir, "src", "plan-ticket.ts"), "YM-1", plan], { cwd: dir, env: { PATH: process.env.PATH, WORKFLOW_COMMENTS: commentsFile, XDG_RUNTIME_DIR: runtime, PI_SESSION_ID: "parent" } })).stdout;
    const reset = () => db.prepare("UPDATE work SET stage='planned' WHERE ticket='YM-1'").run();
    const triggerReview = async () => {
      if (eventConnections.length === 0) await once(eventServer, "connection");
      const socket = eventConnections.at(-1)!;
      const sent = once(socket, "data");
      socket.write("review");
      await sent;
      await new Promise<void>((resolve) => setImmediate(resolve));
    };
    await input("/plan YM-1");
    assert.match(await record(), /plan-only; ready for \/do/);
    const firstPublications = JSON.parse(readFileSync(commentsFile, "utf8")) as { body: string }[];
    assert.equal(firstPublications.length, 2);
    assert.match(firstPublications[0]!.body, /YM-1 · scout · revision/);
    assert.match(firstPublications[1]!.body, /YM-1 · plan · revision/);
    assert.match(firstPublications[1]!.body, /record: planned \(successful local record\)/);
    assert.ok(firstPublications[1]!.body.endsWith(text));
    assert.equal(existsSync(join(dir, "work", "YM-1", "fixture-runs")), false);
    assert.equal(calls, 0);
    assert.match(output(await launch()), /current interactive approval/);
    await input("/do YM-1", "extension");
    await input("/do YM-1", "interactive", "rpc");
    assert.match(output(await launch()), /current interactive approval/);
    extraction = "advance-plan-do";
    await input("Спланируй YM-1 и затем выполни");
    const auto = await record();
    assert.match(auto, /background run [a-f0-9-]+/);
    assert.equal((JSON.parse(readFileSync(commentsFile, "utf8")) as unknown[]).length, 2);
    const autoId = auto.match(/background run ([a-f0-9-]+)/)![1]!;
    assert.equal(readFileSync(join(dir, "work", "YM-1", "fixture-runs"), "utf8").trim(), autoId);
    assert.match(output(await launch()), /already consumed/);
    await cancel(autoId);
    reset();
    set(true);
    await input("Plan and then do YM-1");
    assert.match(await record(), /plan-only; ready for \/do/);
    assert.match(output(await launch()), /current interactive approval/);
    await input("/do YM-1");
    writeFileSync(plan, text + "\nchanged");
    assert.match(output(await launch()), /approval.*changed/);
    writeFileSync(plan, text);
    await input("/do YM-1");
    writeFileSync(plan, text.replace("1. Work", "1. Changed scope"));
    assert.match(output(await launch()), /approval scope changed/);
    writeFileSync(plan, text);
    await input("/do YM-1");
    writeFileSync(plan, text.replace("org/repo", "org/other"));
    assert.match(output(await launch()), /approval repositories changed/);
    writeFileSync(plan, text);
    await input("/do YM-1");
    await input("/plan YM-1");
    assert.match(output(await launch()), /current interactive approval/);
    await input("/do YM-1 запусти на gpt-6-astra, задача сложная");
    const explicit = await launch();
    const explicitId = (explicit.details as { runId: string }).runId;
    assert.ok(explicitId, output(explicit));
    const reportsBeforeReview = reports.length;
    await triggerReview();
    assert.equal(reports.length, reportsBeforeReview);
    await cancel(explicitId);
    reset();
    extraction = "approve-ready-do";
    await input("План согласован, запускай YM-1");
    const approved = await launch();
    const approvedId = (approved.details as { runId: string }).runId;
    assert.ok(approvedId, output(approved));
    writeFileSync(plan, text + "\ncycle changed");
    const bindingBlocked = new Promise<void>((resolve) => { reportReady = resolve; });
    await triggerReview();
    await bindingBlocked;
    reportReady = undefined;
    assert.match(JSON.stringify(reports.at(-1)), /approval (?:scope|content hash) changed/);
    await cancel(approvedId);
    assert.equal(confirms, 0);
    assert.deepEqual(notifications, []);
    assert.equal(readRecordedPlanBinding(dir, "YM-1").path, plan);
    for (const surface of ["typed", "tool", "cli", "pane", "ordinary", "coordinator"]) for (const variant of ["on", "off", "neighbor"]) console.log(`RUNTIME_CASE ${surface}:guardPolicy.workflowApproval:${variant}`);
    db.close();
  } finally {
    await shutdown?.();
    for (const socket of eventConnections) socket.destroy();
    await new Promise<void>((resolve) => eventServer.close(() => resolve()));
    process.argv[1] = script;
    for (const key of Object.keys(process.env)) if (!(key in env)) delete process.env[key];
    Object.assign(process.env, env);
    rmSync(dir, { recursive: true, force: true });
    rmSync(runtime, { recursive: true, force: true });
  }
});
